CREATE DATABASE IF NOT EXISTS BUFFER_JIT;
USE BUFFER_JIT;

CREATE TABLE USUARIOS (
ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_USUARIO VARCHAR(200) NOT NULL,
CORREO VARCHAR(200) NOT NULL UNIQUE,
PASSWORD_USER VARCHAR(200) NOT NULL,
TELEFONO VARCHAR(20),
DIA_CREACION DATETIME,
DIA_MODIFICACION DATETIME
);

CREATE TABLE ROLES (
ID_ROL INT AUTO_INCREMENT PRIMARY KEY,
ROL VARCHAR(100) NOT NULL
);

INSERT INTO ROLES (ROL) VALUES ('ADMIN');
INSERT INTO ROLES (ROL) VALUES ('OPERADOR');

CREATE TABLE USUARIO_ROL (
ID_USUARIO INT,
ID_ROL INT,
PRIMARY KEY (ID_USUARIO, ID_ROL),
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE,
FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL) ON DELETE CASCADE
);

CREATE TABLE MOVIMIENTOS (
ID_MOVIMIENTO INT AUTO_INCREMENT PRIMARY KEY,
FECHA_MOVIMIENTO DATETIME,
CANTIDAD_MOVIMIENTO INT,
TIPO_MOVIMIENTO VARCHAR(100),
ID_USUARIO INT,
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE PROVEEDORES (
ID_PROVEEDOR INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_PROVEEDOR VARCHAR(200),
TELEFONO VARCHAR(20),
RFC VARCHAR(100),
CORREO VARCHAR(200)
);

CREATE TABLE PRODUCTO (
ID_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
CODIGO_PRODUCTO VARCHAR(200),
NOMBRE_PRODUCTO VARCHAR(200),
DESCRIPCION VARCHAR(100),
VALOR_UNITARIO DECIMAL(10,2),
CATEGORIA_ABCD CHAR(1),
DIA_REGISTRO DATETIME,
ID_PROVEEDOR INT,
FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR)
);

CREATE TABLE INVENTARIO (
ID_INVENTARIO INT AUTO_INCREMENT PRIMARY KEY,
STOCK_ACTUAL INT,
ID_PRODUCTO INT,
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE DETALLE_MOVIMIENTO (
ID_DETALLE INT AUTO_INCREMENT PRIMARY KEY,
CANTIDAD INT,
ID_MOVIMIENTO INT,
ID_PRODUCTO INT,
FOREIGN KEY (ID_MOVIMIENTO) REFERENCES MOVIMIENTOS(ID_MOVIMIENTO),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE CODIGO_BARRAS (
ID_CODIGO INT AUTO_INCREMENT PRIMARY KEY,
CODIGO VARCHAR(200),
ID_PRODUCTO INT,
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE DETALLE_ESCANEO (
ID_FECHA_ESCANEO INT AUTO_INCREMENT PRIMARY KEY,
FECHA DATETIME,
TIPO_MOVIMIENTO VARCHAR(200),
ID_CODIGO INT,
FOREIGN KEY (ID_CODIGO) REFERENCES CODIGO_BARRAS(ID_CODIGO)
);