USE BUFFER_JIT;
DROP PROCEDURE IF EXISTS PA_PRODUCTOS_JSON;
DELIMITER $$

CREATE PROCEDURE PA_PRODUCTOS_JSON(
    IN REQ JSON,
    IN PARAMS JSON
)
BEGIN

    DECLARE V_METODO VARCHAR(10);
    DECLARE V_ID_PRODUCTO INT DEFAULT 0;
    DECLARE V_NOMBRE VARCHAR(100);
    DECLARE V_DESCRIPCION TEXT;
    DECLARE V_PRECIO DECIMAL(10,2);
    DECLARE V_CATEGORIA VARCHAR(100);
    DECLARE V_CODIGO VARCHAR(50);
    DECLARE V_ID_PROVEEDOR INT;
    DECLARE V_STOCK INT;
    DECLARE V_AUX_ID INT;

    SET V_METODO = JSON_UNQUOTE(JSON_EXTRACT(REQ,'$.http_method'));
    SET V_ID_PRODUCTO = IFNULL(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.ID_PRODUCTO')),0);

    /* ===================== GET ===================== */

    IF V_METODO = 'GET' THEN

        SELECT 
            P.ID_PRODUCTO,
            P.NOMBRE_PRODUCTO,
            P.DESCRIPCION,
            P.VALOR_UNITARIO,
            P.DIA_REGISTRO,
            P.CODIGO_PRODUCTO,
            P.CATEGORIA_ABCD,
            PR.NOMBRE_PROVEEDOR,
            IFNULL(I.STOCK_ACTUAL,0) AS STOCK_ACTUAL
        FROM PRODUCTO P
        LEFT JOIN PROVEEDORES PR ON P.ID_PROVEEDOR = PR.ID_PROVEEDOR
        LEFT JOIN INVENTARIO I ON I.ID_PRODUCTO = P.ID_PRODUCTO
        WHERE P.ID_PRODUCTO = IF(V_ID_PRODUCTO = 0, P.ID_PRODUCTO, V_ID_PRODUCTO);

    /* ===================== POST ===================== */

    ELSEIF V_METODO = 'POST' THEN

        SET V_NOMBRE = IFNULL(NULLIF(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.NOMBRE_PRODUCTO')),''),'SIN NOMBRE');
        SET V_DESCRIPCION = IFNULL(NULLIF(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.DESCRIPCION')),''),'SIN DESCRIPCION');
        SET V_PRECIO = IFNULL(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.VALOR_UNITARIO')),0);
        SET V_CATEGORIA = IFNULL(NULLIF(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.CATEGORIA_ABCD')),''),'SIN CATEGORIA');
        SET V_CODIGO = IFNULL(NULLIF(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.CODIGO_PRODUCTO')),''),'SIN CODIGO');
        SET V_ID_PROVEEDOR = IFNULL(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.ID_PROVEEDOR')),0);
        SET V_STOCK = IFNULL(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.STOCK_ACTUAL')),0);

        IF V_ID_PROVEEDOR = 0 THEN
            SELECT '400: ID_PROVEEDOR REQUERIDO' AS RESULT;

        ELSEIF NOT EXISTS (SELECT 1 FROM PROVEEDORES WHERE ID_PROVEEDOR = V_ID_PROVEEDOR) THEN
            SELECT '404: PROVEEDOR NO ENCONTRADO' AS RESULT;

        ELSE

            INSERT INTO PRODUCTO(
                NOMBRE_PRODUCTO,
                DESCRIPCION,
                VALOR_UNITARIO,
                DIA_REGISTRO,
                CODIGO_PRODUCTO,
                CATEGORIA_ABCD,
                ID_PROVEEDOR
            )
            VALUES(
                V_NOMBRE,
                V_DESCRIPCION,
                V_PRECIO,
                NOW(),
                V_CODIGO,
                V_CATEGORIA,
                V_ID_PROVEEDOR
            );

            SET V_AUX_ID = LAST_INSERT_ID();

            INSERT INTO INVENTARIO(ID_PRODUCTO,STOCK_ACTUAL)
            VALUES(V_AUX_ID,V_STOCK);

            SELECT CONCAT('201: PRODUCTO CREADO, ID:',V_AUX_ID) AS RESULT;

        END IF;

    /* ===================== PUT ===================== */

    ELSEIF V_METODO = 'PUT' THEN

        IF V_ID_PRODUCTO = 0 THEN
            SELECT '400: ID_PRODUCTO REQUERIDO' AS RESULT;

        ELSEIF NOT EXISTS (SELECT 1 FROM PRODUCTO WHERE ID_PRODUCTO = V_ID_PRODUCTO) THEN
            SELECT '404: PRODUCTO NO ENCONTRADO' AS RESULT;

        ELSE

            UPDATE PRODUCTO
            SET
                NOMBRE_PRODUCTO = COALESCE(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.NOMBRE_PRODUCTO')),NOMBRE_PRODUCTO),
                DESCRIPCION = COALESCE(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.DESCRIPCION')),DESCRIPCION),
                VALOR_UNITARIO = COALESCE(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.VALOR_UNITARIO')),VALOR_UNITARIO),
                CODIGO_PRODUCTO = COALESCE(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.CODIGO_PRODUCTO')),CODIGO_PRODUCTO),
                CATEGORIA_ABCD = COALESCE(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.CATEGORIA_ABCD')),CATEGORIA_ABCD),
                ID_PROVEEDOR = COALESCE(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.ID_PROVEEDOR')),ID_PROVEEDOR)
            WHERE ID_PRODUCTO = V_ID_PRODUCTO;

            IF JSON_EXTRACT(PARAMS,'$.STOCK_ACTUAL') IS NOT NULL THEN
                UPDATE INVENTARIO
                SET STOCK_ACTUAL = JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.STOCK_ACTUAL'))
                WHERE ID_PRODUCTO = V_ID_PRODUCTO;
            END IF;

            SELECT CONCAT('200: PRODUCTO ACTUALIZADO, ID:',V_ID_PRODUCTO) AS RESULT;

        END IF;

    /* ===================== DELETE ===================== */

    ELSEIF V_METODO = 'DELETE' THEN

        IF V_ID_PRODUCTO = 0 THEN
            SELECT '400: ID_PRODUCTO REQUERIDO' AS RESULT;

        ELSE

            DELETE FROM INVENTARIO 
            WHERE ID_PRODUCTO = V_ID_PRODUCTO;

            DELETE FROM PRODUCTO 
            WHERE ID_PRODUCTO = V_ID_PRODUCTO;

            SELECT CONCAT('200: PRODUCTO ELIMINADO, ID:',V_ID_PRODUCTO) AS RESULT;

        END IF;

    ELSE
        SELECT '400: METODO NO SOPORTADO' AS RESULT;

    END IF;

END$$

DELIMITER ;{

/*
CALL PA_PRODUCTOS_JSON(
JSON_OBJECT('http_method','GET'),
JSON_OBJECT('ID_PRODUCTO',0)
);

CALL PA_PRODUCTOS_JSON(
JSON_OBJECT('http_method','POST'),
JSON_OBJECT(
'NOMBRE_PRODUCTO','Camisa',
'DESCRIPCION','Camisa algodón',
'VALOR_UNITARIO',250,
'CODIGO_PRODUCTO','CAM01',
'CATEGORIA_ABCD','ROPA',
'ID_PROVEEDOR',1,
'STOCK_ACTUAL',50
));

CALL PA_PRODUCTOS_JSON(
JSON_OBJECT('http_method','PUT'),
JSON_OBJECT(
'ID_PRODUCTO',6,
'VALOR_UNITARIO',300,
'STOCK_ACTUAL',80
));

CALL PA_PRODUCTOS_JSON(
JSON_OBJECT('http_method','DELETE'),
JSON_OBJECT('ID_PRODUCTO',6)
);
*/