USE BUFFER_JIT;
DROP PROCEDURE IF EXISTS PA_USUARIOS_JSON;

DELIMITER $$

CREATE PROCEDURE PA_USUARIOS_JSON(
    IN REQ JSON,
    IN PARAMS JSON
)
BEGIN

    DECLARE V_METODO VARCHAR(10);
    DECLARE V_ID_USUARIO INT DEFAULT 0;
    DECLARE V_NOMBRE_USUARIO VARCHAR(100);
    DECLARE V_CORREO VARCHAR(150);
    DECLARE V_TELEFONO VARCHAR(20);
    DECLARE V_PASSWORD_USER VARCHAR(200);
    DECLARE V_ID_ROL INT;
    DECLARE V_AUXILIAR_ID INT;

    /* ===================== OBTENER DATOS ===================== */

    SET V_METODO = JSON_UNQUOTE(JSON_EXTRACT(REQ,'$.http_method'));
    SET V_ID_USUARIO = IFNULL(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.ID_USUARIO')),0);

    /* ===================== VALIDAR EXISTENCIA ===================== */

    IF V_ID_USUARIO != 0 
    AND NOT EXISTS (SELECT 1 FROM USUARIOS WHERE ID_USUARIO = V_ID_USUARIO) THEN

        SELECT CONCAT('404: USUARIO NO ENCONTRADO: ',V_ID_USUARIO) AS RESULT;

    ELSE

    /* ===================== GET ===================== */

    IF V_METODO = 'GET' THEN

        SELECT 
            U.ID_USUARIO,
            U.NOMBRE_USUARIO,
            U.CORREO,
            U.TELEFONO,
            U.PASSWORD_USER,
            R.ID_ROL,
            R.ROL
        FROM USUARIOS U
        LEFT JOIN USUARIO_ROL UR 
            ON U.ID_USUARIO = UR.ID_USUARIO
        LEFT JOIN ROLES R
            ON UR.ID_ROL = R.ID_ROL
        WHERE (V_ID_USUARIO = 0 OR U.ID_USUARIO = V_ID_USUARIO);

    /* ===================== POST ===================== */

    ELSEIF V_METODO = 'POST' THEN

        SET V_NOMBRE_USUARIO = IFNULL(NULLIF(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.NOMBRE_USUARIO')),''),'SIN NOMBRE');
        SET V_CORREO = IFNULL(NULLIF(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.CORREO')),''),'SIN CORREO');
        SET V_TELEFONO = IFNULL(NULLIF(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.TELEFONO')),''),'SIN TELEFONO');
        SET V_PASSWORD_USER = IFNULL(NULLIF(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.PASSWORD_USER')),''),'123456');
        SET V_ID_ROL = IFNULL(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.ID_ROL')),2);

        IF EXISTS(SELECT 1 FROM USUARIOS WHERE CORREO = V_CORREO) THEN

            SELECT '409: CORREO YA REGISTRADO' AS RESULT;

        ELSEIF NOT EXISTS (SELECT 1 FROM ROLES WHERE ID_ROL = V_ID_ROL) THEN

            SELECT '404: ROL NO ENCONTRADO' AS RESULT;

        ELSE

            INSERT INTO USUARIOS (NOMBRE_USUARIO,CORREO,TELEFONO,PASSWORD_USER,DIA_CREACION, DIA_MODIFICACION)
            VALUES (V_NOMBRE_USUARIO,V_CORREO,V_TELEFONO,V_PASSWORD_USER,NOW(),NOW());

            SET V_AUXILIAR_ID = LAST_INSERT_ID();

            INSERT INTO USUARIO_ROL (ID_USUARIO,ID_ROL)
            VALUES (V_AUXILIAR_ID,V_ID_ROL);

            SELECT CONCAT('201: USUARIO CREADO, ID:',V_AUXILIAR_ID) AS RESULT;

        END IF;

    /* ===================== PUT ===================== */

    ELSEIF V_METODO = 'PUT' THEN

        IF V_ID_USUARIO = 0 THEN

            SELECT '400: ID_USUARIO REQUERIDO' AS RESULT;

        ELSE

            UPDATE USUARIOS
            SET
                NOMBRE_USUARIO = COALESCE(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.NOMBRE_USUARIO')),NOMBRE_USUARIO),
                CORREO = COALESCE(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.CORREO')),CORREO),
                TELEFONO = COALESCE(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.TELEFONO')),TELEFONO),
                PASSWORD_USER = COALESCE(JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.PASSWORD_USER')),PASSWORD_USER),
                DIA_MODIFICACION = NOW()
            WHERE ID_USUARIO = V_ID_USUARIO;

            IF JSON_EXTRACT(PARAMS,'$.ID_ROL') IS NOT NULL THEN

                DELETE FROM USUARIO_ROL
                WHERE ID_USUARIO = V_ID_USUARIO;

                INSERT INTO USUARIO_ROL(ID_USUARIO,ID_ROL)
                VALUES(
                    V_ID_USUARIO,
                    JSON_UNQUOTE(JSON_EXTRACT(PARAMS,'$.ID_ROL'))
                );

            END IF;

            SELECT CONCAT('200: USUARIO ACTUALIZADO, ID:',V_ID_USUARIO) AS RESULT;

        END IF;

    /* ===================== DELETE ===================== */

    ELSEIF V_METODO = 'DEL' THEN

        IF V_ID_USUARIO = 0 THEN

            SELECT '400: ID_USUARIO REQUERIDO' AS RESULT;

        ELSE

            DELETE FROM USUARIO_ROL
            WHERE ID_USUARIO = V_ID_USUARIO;

            DELETE FROM USUARIOS
            WHERE ID_USUARIO = V_ID_USUARIO;

            SELECT CONCAT('200: USUARIO ELIMINADO, ID:',V_ID_USUARIO) AS RESULT;

        END IF;

    ELSE

        SELECT 'ERROR: METODO NO SOPORTADO' AS RESULT;

    END IF;

    END IF;

END $$

DELIMITER ;
/*
CALL PA_USUARIOS_JSON(
    JSON_OBJECT('http_method','GET'),
    JSON_OBJECT()
);
CALL PA_USUARIOS_JSON(
    JSON_OBJECT('http_method', 'POST'),
    JSON_OBJECT(
        'NOMBRE_USUARIO', 'Dara',
        'CORREO', 'Dara@Marciana.com',
        'PASSWORD_USER', '12345',
        'TELEFONO', '9981234567',
        'ID_ROL',1
    )
);
CALL PA_USUARIOS_JSON(
    JSON_OBJECT('http_method','PUT'),
    JSON_OBJECT(
        'ID_USUARIO',6,
        'NOMBRE_USUARIO','DARA ME DEBE 2300',
        'ID_ROL',2
    )
);
CALL PA_USUARIOS_JSON(
    JSON_OBJECT('http_method','DEL'),
    JSON_OBJECT('ID_USUARIO',3)
); */
